### PR TITLE
+Shape +Mass +Friction

### PR DESCRIPTION
**Pull request by daniel86**
second try...
Shape, Mass, Friction defined as physical attributes which are regions. Note that DUL enforces that qualities are not used at all (i.e. *PhysicalAttribute is-region-of only PhysicalObject*).

### CODE REVIEW

**Comment by porzel** [comment]
Seems OK.

**Comment by porzel** [comment]
Please use the naming converntion *Region or *Attribute for subregions, e.g. densitiyRegion or densityAttribute and leave the term Density for the Quality (if we ever need/want to model them as well.

**Comment by daniel86** [comment]
> Please use the naming converntion *Region or *Attribute for subregions, e.g. densitiyRegion or densityAttribute and leave the term Density for the Quality (if we ever need/want to model them as well.

done

**Comment by daniel86** [comment]
> > Please use the naming converntion *Region or *Attribute for subregions, e.g. densitiyRegion or densityAttribute and leave the term Density for the Quality (if we ever need/want to model them as well.
> 
> done

oh I forgot the properties

**Comment by daniel86** [comment]
> > > Please use the naming converntion *Region or *Attribute for subregions, e.g. densitiyRegion or densityAttribute and leave the term Density for the Quality (if we ever need/want to model them as well.
> > 
> > 
> > done
> 
> oh I forgot the properties

now its done

**Pull request merged**
